apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging
  namespace: default
spec:
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: cert-testing
  dnsNames:
  - sohan.nikhilspace.tech