apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "pod-mtls"
  namespace: default
spec:
  selector:
    matchLabels:
      version: v1
  portLevelMtls:
    80:
      mode: STRICT