apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ninja
  labels:
    app: "ninja"
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  "nginx"
  template:
    metadata:
      name: "nginx"
      labels:
        app: "nginx"
    spec:
      containers:
      - name: "nginx"
        image: "dogra21703/istio-header:v3"
        ports:
        - containerPort: 80