apiVersion: v1
kind: Service
metadata:
  name: nginx
spec: 
  selector:
    app: "nginx"
  type: LoadBalancer # | ClusterIP | NodePort
  ports:
    - port: 80   #ServicePort
      targetPort: 80   #containerPort 
      nodePort: 32767    #30000-32767