apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: review
spec:
  selector:
    istio: ingressgateway    
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "test.bookinfo.com"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "test.bookinfo.com"
      tls:
        mode: SIMPLE
        credentialName: test-bookinfo-certs
