apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-virtual-service
spec:
  hosts:
    - "bookinfo.com"   
  gateways:
    - "review"
    - mesh
  http:
  - timeout: 0.001s
    fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 10s
    match:
      - headers:
          user:
            exact: v1
    route:
    - destination:
        host: review-svc
        subset: v1
  - timeout: 0.001s
    fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 20s
    match:
      - headers:
          user:
            exact: v2
    route:
    - destination:
        host: review-svc
        subset: v2
