apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: header-svc
spec:
  host:  header-svc
  # trafficPolicy:
  #   loadBalancer:
  #     simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      loadBalancer:
        # simple: ROUND_ROBIN
        consistentHash:
          httpCookie:
            name: user 
            ttl: 1800s  #lifetime of cookies 
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      loadBalancer:
        simple: RANDOM
  - name: v3
    labels:
      version: v3
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN