apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-virtual-service
spec:
  hosts:
    - "sohan.com"   
  gateways:
    - "header"
    - mesh
  http:
  - fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 10s
    match:
      - headers:
          user:
            exact: v1
    route:
    - destination:
        host: header-svc
        subset: v1
  - fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 20s
    match:
      - headers:
          user:
            exact: v2
    route:
    - destination:
        host: header-svc
        subset: v2
  - route:
    - destination:
        host: header-svc 
        subset: v3