apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-virtual-service
spec:
  hosts:
    - "istio-lab.com"   
  gateways:
    - "header"
    - mesh
  http:
  - match:
      - headers:
          user:
            exact: v1
    route:
    - destination:
        host: header-svc
        subset: v1
  - match:
      - headers:
          user:
            exact: v2
    route:
    - destination:
        host: header-svc
        subset: v2
  - route:
    - destination:
        host: header-svc 
        subset: v3